baseURL = "https://ca.shoogle.net/yukon"
languageCode = "en-US"
title = "Yukon"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "yukon"
